soolzzak/BE

- README.md
- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/zzan/global/jwt/JwtAuthFilter.java
- src/main/java/com/example/zzan/global/util/JwtUtil.java
- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/dto/RoomRequestDto.java
- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/room/entity/Category.java
- src/main/java/com/example/zzan/room/entity/GenderSetting.java
- src/main/java/com/example/zzan/room/entity/Room.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/user/dto/UserRequestDto.java
- src/main/java/com/example/zzan/user/entity/Gender.java
- src/main/java/com/example/zzan/user/entity/User.java
- src/main/java/com/example/zzan/user/service/UserService.java
fixes: ERD 2차 수정 및 ENUM 테이블 생성 완료
> fixes: ERD 2차 수정 및 ENUM 테이블 생성 완료

- src/main/java/com/example/zzan/follow/entity/Follow.java
- src/main/java/com/example/zzan/follow/repository/FollowRepository.java
- src/main/java/com/example/zzan/follow/service/FollowService.java
- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
- src/main/java/com/example/zzan/user/entity/User.java
> FEAT: SSE 기능 구현

- build.gradle
- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/webRtc/config/WebRtcConfig.java
- src/main/java/com/example/zzan/webRtc/dto/UserListMap.java
- src/main/java/com/example/zzan/webRtc/dto/WebSocketMessage.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
- src/main/java/com/example/zzan/webRtc/service/RtcChatService.java
> Feat: WebRTC 기능 추가

- src/main/java/com/example/zzan/mypage/service/S3Uploader.java
- src/main/java/com/example/zzan/room/dto/RoomRequestDto.java
- src/main/java/com/example/zzan/room/service/RoomService.java
fix: 카카오 로그인 기능 추가 , Room 이미지 선택 없이 진행시 랜덤 이미지 추가
> fix: 카카오 로그인 기능 추가 , Room 이미지 선택 없이 진행시 랜덤 이미지 추가 

- src/main/java/com/example/zzan/global/exception/ExceptionEnum.java
- src/main/java/com/example/zzan/global/util/JwtUtil.java
- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/room/entity/Room.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/user/entity/User.java
Feat: GuestUser 여부 확인 및 GuestUser leaveRoom 기능 구현 완료
> Feat: GuestUser 여부 확인 및 GuestUser leaveRoom 기능 구현 완료

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
> Feature: roomSetting 옵션 기능 구현

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/global/security/controller/TokenController.java
- src/main/java/com/example/zzan/global/security/dto/TokenDto.java
- src/main/java/com/example/zzan/user/controller/UserController.java
Feat: JWT AccessToken 재발급 기능 구현 / Fixes: WebSecurityConfig 수정
> Feat: JWT AccessToken 재발급 기능 구현 / Fixes: WebSecurityConfig 수정

- src/main/java/com/example/zzan/global/util/JwtUtil.java
> Fixes: JWT 토큰헤더 gender 정보 포함

- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/room/entity/Room.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/service/SseService.java
- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/dto/UserRequestDto.java
Fixes: Room Capacity boolean에서 int로 수정완료
> Fixes: Room Capacity boolean에서 int로 수정완료

- src/main/java/com/example/zzan/follow/controller/FollowController.java
- src/main/java/com/example/zzan/follow/service/FollowService.java
- src/main/java/com/example/zzan/mypage/dto/MyPageResponseDto.java
- src/main/java/com/example/zzan/mypage/dto/RelatedUserResponseDto.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
- src/main/java/com/example/zzan/report/controller/ReportController.java
Fixes: FollowController 한개로 수정 PUT Method 적용 / api 수정 / 상세 유저 페이지에 Follow 여부 확인
> Fixes: FollowController 한개로 수정 / 상세 유저 페이지 Follow 여부 확인

- src/main/java/com/example/zzan/blocklist/controller/BlockListController.java
- src/main/java/com/example/zzan/blocklist/repository/BlockListRepository.java
- src/main/java/com/example/zzan/blocklist/service/BlockListService.java
- src/main/java/com/example/zzan/global/exception/ExceptionEnum.java
- src/main/java/com/example/zzan/mypage/dto/RelatedUserResponseDto.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
Fixes: Block/Unblock 기능 구현 / 상대 상세조회 차단 여부 기능 구현 완료
> Fixes: Block/Unblock 기능 구현 / 상대 상세조회 차단 여부 기능 구현 완료

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
> Fixes: roomSetting 필터 수정 완료

- src/main/java/com/example/zzan/blocklist/controller/BlockListController.java
- src/main/java/com/example/zzan/blocklist/dto/BlockListDto.java
- src/main/java/com/example/zzan/blocklist/entity/BlockList.java
- src/main/java/com/example/zzan/blocklist/repository/BlockListRepository.java
- src/main/java/com/example/zzan/blocklist/service/BlockListService.java
- src/main/java/com/example/zzan/follow/dto/FollowResponseDto.java
- src/main/java/com/example/zzan/follow/repository/FollowRepository.java
- src/main/java/com/example/zzan/follow/service/FollowService.java
- src/main/java/com/example/zzan/global/security/controller/TokenController.java
- src/main/java/com/example/zzan/mypage/dto/RelatedUserResponseDto.java
- src/main/java/com/example/zzan/report/controller/ReportController.java
- src/main/java/com/example/zzan/report/entity/Report.java
- src/main/java/com/example/zzan/report/repository/ReportRepository.java
- src/main/java/com/example/zzan/report/service/ReportService.java
- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/room/entity/Room.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
> Fixes: unused import delete

- src/main/java/com/example/zzan/webRtc/dto/SessionListMap.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
- src/main/java/com/example/zzan/webRtc/service/RtcChatService.java
> Fixes: roomLeave 위한 시그널 채널 수정

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/global/util/JwtUtil.java
- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/dto/KakaoInfoDto.java
- src/main/java/com/example/zzan/user/entity/KakaoUser.java
- src/main/java/com/example/zzan/user/entity/User.java
- src/main/java/com/example/zzan/user/repository/KakaoUserRepository.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
> Feat: 카카오 소셜로그인 기본틀 구현 완료

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
Feat: 카카오 소셜로그인 redirect 주소 변경
> Feat: 카카오 소셜로그인 redirect 주소 변경

- src/main/java/com/example/zzan/global/util/JwtUtil.java
- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
Feat: 카카오 소셜로그인에 필요한 jwt 수정 완료
> Feat: 카카오 소셜로그인에 필요한 jwt 수정 완료

- src/main/java/com/example/zzan/global/util/JwtUtil.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
> Fix: 카카오 소셜로그인 토큰에 유저정보 추가

- src/main/java/com/example/zzan/user/service/KakaoService.java
> Fix: redirect 토큰 쿠키 저장

- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
> Fix: 카카오 로그인 컨트롤러 수정완료

- src/main/java/com/example/zzan/user/service/KakaoService.java
> Fix: 카카오 로그인 컨트롤러 2차 수정완료

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/entity/Category.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
Fix: chooseCategory, getRoomBySetting 합치고 filter 기능 구현 완료
> Fix: chooseCategory, getRoomBySetting 합치고 filter 기능 구현 완료

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/entity/Category.java
- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
Fix: getRooms에 room filter 기능 추가 / Category에서 ALL 삭제
> Fix: getRooms에 room filter 기능 추가 / Category에서 ALL 삭제

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
- src/main/java/com/example/zzan/mypage/dto/MyPageResponseDto.java
- src/main/java/com/example/zzan/room/dto/RoomResponseDto.java
- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
Refactor: userImageUrl -> userImage로 수정 완료
> Refactor: userImageUrl -> userImage로 수정 완료

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/dto/RoomCheckResponseDto.java
- src/main/java/com/example/zzan/room/service/RoomService.java
Refactor: roomCheck API 추가 -> 입장전 인원 수 확인
> Refactor: roomCheck API 추가 -> 입장전 인원 수 확인

- src/main/java/com/example/zzan/room/service/RoomService.java
Refactor: roomCapacity(0)으로 수정 완료
> Refactor: roomCapacity(0)으로 수정 완료

- src/main/java/com/example/zzan/user/controller/UserController.java
- src/main/java/com/example/zzan/user/service/KakaoService.java
> Refactor: 카카오 로그인 컨트롤러 수정

- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
- src/test/java/com/example/zzan/user/SignupTest.java
Feat: Test Code 구축 -> SignupTest
> Feat: Test Code 구축 -> SignupTest

- src/main/java/com/example/zzan/game/controller/GameController.java
- src/main/java/com/example/zzan/game/service/GameService.java
- src/main/java/com/example/zzan/mypage/dto/MyPageResponseDto.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
- src/main/java/com/example/zzan/report/service/ReportService.java
Feat: Game 기본 패키지 생성  
Fix: Mypage 소셜로그인 부분 추가하여 반환
> Feat: Game 기본 패키지 생성 

- src/main/java/com/example/zzan/report/service/ReportService.java
Fix: ExceptionEnum 2차 수정 w/ 지현님
> Fix: ExceptionEnum 2차 수정 w/ 지현님

- src/main/java/com/example/zzan/game/IdiomGameService.java
> Fix: 불필요 로그 삭제

- src/test/java/com/example/zzan/user/LoginTest.java
> Feat : LoginTest 추가 /w. 현경님

- src/main/java/com/example/zzan/room/service/RoomService.java
Fix: GuestUser 입장시 enterRoom메소드에 비밀번호 체크 기능 구현 w/ 지현님
> Fix: GuestUser 입장시 enterRoom메소드에 비밀번호 체크 기능 구현 w/ 지현님

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/service/RoomService.java
> Fix: 방입장 비번 controller 수정

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/user/service/UserService.java
Fix: GuestUser 입장시 enterRoom메소드 변수명 변경 / 닉네임 유효성 검사 구축 w/ 지현님
> Fix: GuestUser 입장시 enterRoom메소드 변수명 변경 / 닉네임 유효성 검사 구축 w/ 지현님

- src/main/java/com/example/zzan/user/controller/UserController.java
Fix : checkUsername controller 구축
> Fix : checkUsername controller 구축

- src/main/java/com/example/zzan/room/entity/Room.java
- src/main/java/com/example/zzan/room/service/RoomService.java
Fix: enterRoom 비밀번호 예외처리 수정
Fix: roomPassword nullable 허용
> Fix: enterRoom 비밀번호 예외처리 수정

- src/main/java/com/example/zzan/room/controller/RoomController.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
Feat: roomEnter 전 passwordCheck API 추가
> Feat: roomEnter 전 passwordCheck API 추가

- src/main/java/com/example/zzan/userHistory/repository/UserHistoryRepository.java
> Fix: UserHistoryRepository 수정

- src/main/java/com/example/zzan/room/controller/RoomController.java
> Fix: Category 내림차순으로 정렬되게 수정

- src/main/java/com/example/zzan/mypage/service/MyPageService.java
Refactor: 전체 코드 refactoring 진행 w/ 지현님, 상우님
> Refactor: 전체 코드 refactoring 진행 w/ 지현님, 상우님

- src/main/java/com/example/zzan/follow/service/FollowService.java
- src/main/java/com/example/zzan/global/exception/ExceptionEnum.java
- src/main/java/com/example/zzan/message/controller/MessageController.java
- src/main/java/com/example/zzan/message/dto/MessageCheckResponseDto.java
- src/main/java/com/example/zzan/message/dto/MessageSendRequestDto.java
- src/main/java/com/example/zzan/message/entity/Messages.java
- src/main/java/com/example/zzan/message/repository/MessageRepository.java
- src/main/java/com/example/zzan/message/service/MessageCheckService.java
- src/main/java/com/example/zzan/message/service/MessageSendService.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
- src/main/java/com/example/zzan/user/repository/UserRepository.java
- src/main/java/com/example/zzan/user/service/UserService.java
- src/test/java/com/example/zzan/room/UpdateRoomTest.java
> Feat : 쪽지 기능 추가 w/ 지현님, 상우님

- src/main/java/com/example/zzan/message/controller/MessageController.java
- src/main/java/com/example/zzan/message/service/MessageCheckService.java
> Fix : 쪽지 기능 수정

- src/main/java/com/example/zzan/sse/controller/SseController.java
> Fix: SSE 컨트롤러 accessKey로 수정

- src/main/java/com/example/zzan/global/config/WebSecurityConfig.java
Fix: SSE 관련하여 WebSecurityConfig 수정
> Fix: SSE 관련하여 WebSecurityConfig 수정

- src/main/java/com/example/zzan/game/IdiomGameService.java
> Fix : gameService 수정 w/ 상우님

- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: SSE service 수정

- src/main/java/com/example/zzan/game/IdiomGameService.java
> Fix : game 순환참조 해결3 w/상우님

- src/main/java/com/example/zzan/game/IdiomGameService.java
> Fix : GameService 수정 w/상우님

- src/main/java/com/example/zzan/game/IdiomGameService.java
- src/main/java/com/example/zzan/game/dto/GameResponseDto.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
Fix : gameResponseDto 수정 w/상우님
> Fix : gameResponseDto 수정 w/상우님

- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: SSE service username->userId
> Fix: SSE service username->userId

- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: SSE service username-> room alarm 위치 변경
> Fix: SSE service username-> room alarm 위치 변경

- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: SSE service ROOM 추가 및 수정

- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: SSE service room.username에서 room.getHostUser.getUsername으로 변경
> Fix: SSE service room.username에서 room.getHostUser.getUsername으로 변경

- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: SSE service log 추가 (추후 삭제 예정)
> Fix: SSE service log 추가 (추후 삭제 예정)

- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: this.followService null 처리
> Fix: this.followService null 처리

- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: log 추가 (확인 후 삭제 예정)

- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: roomService 및 SSE service 수정
> Fix: roomService 및 SSE service 수정

- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/controller/SseController.java
- src/main/java/com/example/zzan/sse/service/SseService.java
Fix: SSE 메세지 위치 파악을 위한 로그 (추후 삭제 예정)
> Fix: SSE 메세지 위치 파악을 위한 로그 (추후 삭제 예정)

- src/main/java/com/example/zzan/room/repository/RoomRepository.java
- src/main/java/com/example/zzan/room/service/RoomService.java
- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: SSE 메세지 보내기 및 log 삭제

- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: SSE 메세지에 roomId 보내기

- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: SSE 메세지에 roomId 따로 보내기

- src/main/java/com/example/zzan/game/IdiomGameService.java
Fix: Idiom setting in the startGame method
> Fix: Idiom setting in the startGame method

- src/main/java/com/example/zzan/game/IdiomGameService.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
> Fix : gameService 줄맞춤 및 주석 정리/타이머 3,2,1도 반환

- src/main/java/com/example/zzan/global/exception/ExceptionEnum.java
- src/main/java/com/example/zzan/mypage/controller/MyPageController.java
- src/main/java/com/example/zzan/mypage/dto/MyPageResponseDto.java
- src/main/java/com/example/zzan/mypage/dto/MypageChangeDto.java
- src/main/java/com/example/zzan/mypage/dto/RelatedUserResponseDto.java
- src/main/java/com/example/zzan/mypage/dto/UserSearchDto.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
- src/main/java/com/example/zzan/user/entity/User.java
- src/main/java/com/example/zzan/user/repository/UserRepository.java
Feat: 마이페이지 한줄 소개 추가, 유저 찾기 기능 추가
> Feat: 마이페이지 한줄 소개 추가, 유저 찾기 기능 추가

- src/main/java/com/example/zzan/game/IdiomGameService.java
- src/main/java/com/example/zzan/game/dto/GameResponseDto.java
- src/main/java/com/example/zzan/webRtc/rtc/SignalHandler.java
Fix : 카운트 int로 변경, pauseGame&stopGame 추가
> Fix : 카운트 int로 변경, pauseGame&stopGame 추가

- src/main/java/com/example/zzan/message/repository/MessageRepository.java
- src/main/java/com/example/zzan/message/service/MessageCheckService.java
- src/main/java/com/example/zzan/message/service/MessageSendService.java
- src/main/java/com/example/zzan/sse/service/SseService.java
> Fix: 쪽지 최신순으로 받기 구현

- src/main/java/com/example/zzan/mypage/service/MyPageService.java
> Fix: mypage 이미지 압축 -  gif 제외

- src/main/java/com/example/zzan/mypage/controller/MyPageController.java
- src/main/java/com/example/zzan/mypage/service/MyPageService.java
- src/main/java/com/example/zzan/user/repository/UserRepository.java
> Fix: 정확하게 유저네임 검색하게 유저 서치 수정
